#!/bin/bash

set -ex

./scripts/version_bump
export version=`cat VERSION`
cat wco_models.gemspec-template | \
  sed -e "s/\$version/$version/g" > wco_models.gemspec

bundle

git add .
git commit -m 'autobuild `date "+%Y%m%d"`'
git push

gem build wco_models.gemspec
gem push wco_models-$version.gem

rm wco_models-`cat VERSION`.gem

echo "wco_models build ok"
